---

- name: copy gpu_stat.py
  copy: src=gpu_stat.py dest="{{ sacctgpu_bin }}/gpu_stat.py" owner=root group=root mode="0744"

- name: copy jobinfo.py
  copy: src=jobinfo.py dest="{{ sacctgpu_bin }}/jobinfo.py" owner=root group=root mode="0755"

- name: create sacctgpu.service
  ansible.builtin.template:
    src: sacctgpu.service.j2
    dest: /lib/systemd/system/sacctgpu.service

- name: create sacctgpu.timer
  ansible.builtin.template:
    src: sacctgpu.timer.j2
    dest: /lib/systemd/system/sacctgpu.timer

- name: restart sacctgpu.service
  ansible.builtin.systemd:
    state: "{{ sacctgpu_timer_state }}"
    daemon_reload: true
    name: sacctgpu.service
    enabled: true

- name: restart sacctgpu.timer
  ansible.builtin.systemd:
    state: "{{ sacctgpu_timer_state }}"
    daemon_reload: true
    name: sacctgpu.timer

- name: Set content fact
  set_fact:
    sacctgpu_content: "{{ lookup('file', 'files/epilog.sh') }}"

- name: Add call to Epilog
  blockinfile:
    path: "{{ sacctgpu_epilog }}"
    content: '{{ sacctgpu_content }}'
    state: present
    insertafter: 'sacctgpu marker'

