---

- name: copy gpu_stat.py
  copy: src=gpu_stat.py dest="{{ sacctgpu_bin }}/gpu_stat.py" owner=root group=root mode="0744"

- name: copy jobinfo.py
  copy: src=jobinfo.py dest="{{ sacctgpu_bin }}/jobinfo.py" owner=root group=root mode="0755"

- name: Ensure gpu_stats collects data every minute
  cron:
    name: "gpu_stats collect data"
    job: "{{ sacctgpu_bin }}/gpu_stat.py > /dev/null"
    state: "present"

- name: Set content fact
  set_fact:
    sacctgpu_content: "{{ lookup('file', 'files/epilog.sh') }}"

- name: Add call to Epilog
  blockinfile:
    path: "{{ sacctgpu_epilog }}"
    content: '{{ sacctgpu_content }}'
    state: present

